site_title: "移个朋友·巴黎创业"
site_subtitle: "巴黎创业故事与资源知识库"
site_description: "分享在巴黎创业的故事、经验和资源，帮助更多华人在法国实现创业梦想"
contact_email: "contact@example.com"
social_media:
  wechat: "移个朋友"
  weibo: ""
  xiaohongshu: ""
